name: maskgit
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pip
  - cudatoolkit
  - pytorch
  - torchvision
  - pytorch-cuda
  - pip:
      - torch-fidelity
      - matplotlib
      - seaborn
      - tqdm
      - pillow
      - scikit-learn
      - clip
      - pytorch-lightning
      - omegaconf
      - einops
      - webdataset
